### ISSUE TITLE
Automated PyPI Publication

### ISSUE THREAD

**Issue by NeonDaniel** [MycroftAI/mycroft-messagebus-client#41]
**Is your feature request related to a problem? Please describe.**
It looks like there is an automation for tagging releases on GitHub, but nothing for pushing new versions to PyPI.

**Describe the solution you'd like**
An automation to push to PyPI would ensure that merged changes are immediately available for use as dependencies in other Python packages. Versioning should already have been reviewed by the time a release is tagged and automation keeps releases in sync with PyPI.

**Describe alternatives you've considered**
Manual updates are always an option

**Additional context**
I have implemented this automation in several repositories, i.e.: https://github.com/NeonGeckoCom/neon-skill-utils/blob/dev/.github/workflows/publish_release.yml

**Comment by forslund** [comment]
There is a github action in place for that. it is triggered when the setup.py version is updated. (if I recall correctly)

**Comment by krisgesling** [comment]
Yeah, it's handled in this action: 
https://github.com/MycroftAI/mycroft-messagebus-client/blob/master/.github/workflows/push.yml

We're bumping the version in the collect responses PR which will trigger a new release.

We don't currently do an automated increment of versions which I assume OVOS do for all the alpha's that get pushed out, but I'm personally not really sold on the value of that either. 

We do want to standardize this across the organization, and I anticipate that we'll publish Github Actions for this purpose, rather than trying to keep files synced across all the repo's.
